### ISSUE TITLE
A object's base has a `getter` property unable to display value in debug variable view

### ISSUE THREAD

**Issue by thqby** [zero-plusplus/vscode-autohotkey-debug#108] opened 2021-07-07 04:55 UTC
![image](https://user-images.githubusercontent.com/28240311/124701049-7502d700-df20-11eb-925c-cef3a5ab727e.png)

**Comment by zero-plusplus** [comment] 2021-07-07 06:00
This issue occurs with dynamic properties.
The AutoHotkey debugger has some issues with dynamic properties (unless my implementation is bad), and returning this "<error>" is one of them.

I came up with an idea to work around this problem and implemented it, and was able to get the correct value.
However, it may break the workaround process for another problem that is already implemented, so I need time to adjust it. In some cases, I might abandon the fix for this issue.

**Comment by thqby** [comment] 2021-07-07 06:22
I found that the dynamic properties value can be displayed normally in `cweijan.vscode-autohotkey-plus` extension

**Comment by zero-plusplus** [comment] 2021-07-07 07:20
Thanks for the information.

I implemented its debugger in a fairly straightforward way, but in that case, the issue does not seem to occur.
In other words, it seems to be caused by a workaround process for another issue.

The another issue is specifically the following
* #50
* #51

The dynamic property issue is very mysterious and may still take some time to resolve.

**Comment by thqby** [comment] 2021-07-07 09:25
The previous version is working fine.
![image](https://user-images.githubusercontent.com/28240311/124734849-16515380-df48-11eb-9ae5-de952b73733d.png)

**Comment by zero-plusplus** [comment] 2021-07-07 11:07
Thanks for the further information. I've just checked.

I was able to find the fix, but it needs to be done carefully because if I simply fix it, it will affect the functionality of 1.6.10.

Also, I may be able to fix the current inefficient way of getting dynamic properties now that I understand a little more about them.

**Comment by zero-plusplus** [comment] 2021-07-08 05:19
I have found the cause of the issue and will leave it as a note.

The AutoHotkey debugger manages the base object with a special name, `<base>`, but can use `base` instead, just as in the script specification.

This is where the issue was this time. When retrieving a dynamic property, `myBuffer.<base>.Ptr` works fine, but `myBuffer.base.Ptr` causes an error.

I had to convert from `<base>` to `base` to fix the issue in #50. This issue seems to have started here.

---

This fix has simplified the source code and greatly improved performance.
If there are no troubles, a fixed version will be released in a few days.

**Closed** 2021-07-08 12:21 UTC
Labels: bug, v2only
