### ISSUE TITLE
Expand variable categories on debug

### ISSUE THREAD

**Issue by anonymous1184** [zero-plusplus/vscode-autohotkey-debug#222] opened 2022-06-16 19:10 UTC
Is there a way to automatically expand `local` variables once inside a function/method when debugging (same as `static`? Otherwise one needs to manually expand after entering each function.

**Comment by zero-plusplus** [comment] 2022-06-16 22:54
If within a function, aren't local variables auto-expanded?
On the contrary, the second and subsequent ones such as static and global are not auto-expanded.

I tried to change the variable list to auto-expand according to the current scope because this specification was inconvenient in the past, but it seems that this is not possible due to VSCode specifications.

**Comment by anonymous1184** [comment] 2022-06-18 14:57
I get `Static` (at the top, which I'm grateful as makes sense having in the first place given that those variables are set on load) and then `Local`, `Global` and `Built-in`. The configuration is on the `.json` has `variableCategories` set to `recommend`.

I can record a small video/gif if needed.

Thanks!

**Comment by zero-plusplus** [comment] 2022-06-18 15:15
I don't understand the situation a bit.

Please give us the minimum source code and full contents of launch.json that can reproduce your situation.

**Comment by anonymous1184** [comment] 2022-06-18 16:02
I use AHK_H because I want the `static` scope distinguished and because I make use of its features.

Here are the files: [test.zip][1], and little demo. As you can see `Static` comes first expanded, I want to keep it like so and also expand `Local`:

https://user-images.githubusercontent.com/53758552/174446665-e4b468d3-b6d4-45da-b659-ae67a1c63067.mp4

[1]: https://github.com/zero-plusplus/vscode-autohotkey-debug/files/8933915/test.zip

**Comment by zero-plusplus** [comment] 2022-06-19 11:16
I tried but could not confirm it in my environment.

The VRIABLES pane shows `Local`, `Static`, `Global`, and `Built-in Global` in that order.

**Comment by anonymous1184** [comment] 2022-06-19 19:18
Regardless of the order... is there any way to auto expand both `Static` and `Local`?

**Comment by zero-plusplus** [comment] 2022-06-20 04:28
I have not looked into the detailed specifications, but as far as I can see, only the topmost `Scope` automatically expanded.

Therefore, the order is important.

And since there is no way to deploy the scope from the extension side, it is impossible to deploy both.

**Comment by anonymous1184** [comment] 2022-06-22 04:00
Thanks a lot for the info. Feel free to close the issue if is impossible to accomplish.

**Comment by zero-plusplus** [comment] 2022-06-22 05:30
OK. I close this issue once.

Also, I set a label to make it easier to find, as there may come a day in the future when VSCode can be updated to resolve this issue.

**Closed by zero-plusplus** 2022-06-22 05:30 UTC
