### ISSUE TITLE
Debug Console: Hyperlink to error line

### ISSUE THREAD

**Issue by SAbboushi** [zero-plusplus/vscode-autohotkey-debug#12] opened 2020-06-12 15:14 UTC
Parentheses and spaces in path (folder name or file name) breaks Hyperlink to error line.
I did not test other non-alpha characters that are valid for folder/file names.

Examples:
"D:\Documents\GAR\New folder (2)\
"D:\Documents\GAR\Newfolder2\Untitled 2.ahk"

For future issues, do you have preference:

- Re-open Debug Console: Hyperlink to error line #10, or
- Submit new issue as I have done here

I am missing this feature very much as I am fixing scripts to be compatible with new AHK version which has broken (almost all of) my scripts!!

**Comment by zero-plusplus** [comment] 2020-06-13 01:29
It is a bug that should be fixed that the output is a little strange when using parenthesized paths.

For paths with spaces, I've checked in the Node debugger, but those paths didn't create links.
This is probably by design.
The only way to avoid this problem is to use paths that do not use spaces.

I also checked the file of multi-byte character strings. In that case, the file name is displayed as `?`, but this is probably the specification because it is the same for SciTE4AutoHotkey.

**Comment by zero-plusplus** [comment] 2020-06-13 02:20
> For future issues, do you have preference
It seems that you need to have permission to reopen it.
So you may create a new one.

**Comment by SAbboushi** [comment] 2020-06-16 12:33
Still problems.
1)
Path: "D:\Documents\GAR\New folder (2)\Untitled - 1.ahk"
Folder has spaces and parentheses
File name has spaces
**Error hyperlink is to AutoHotkeyU64.exe**
**Line number of error (11) is not mentioned on error line in DEBUG CONSOLE**

![image](https://user-images.githubusercontent.com/1964198/84773213-b638e980-afa1-11ea-94ec-a3a9ba7c0158.png)

2)
Path: "D:\Documents\GAR\Newfolder2\Untitled1.ahk"
Folder has no spaces or parentheses
File name has no spaces
**Error line has two hyperlinks: First Error hyperlink is to AutoHotkeyU64.exe**
**Second Error hyperlink is to "Untitled1.ahk" but without Line number of error (11)**

![image](https://user-images.githubusercontent.com/1964198/84774176-111f1080-afa3-11ea-927b-b9230f928671.png)

**Comment by zero-plusplus** [comment] 2020-06-16 13:24
This is not a problem. It is a specification.
In case of an error that occurs during execution, for some reason AutoHotkey does not output the file path information.

The line shown in yellow only shows the command when executing AutoHotkey, not the error output.

By the way, another problem, try `throw Excepton("")`. Only the message box appears, and the contents are not output. This is probably also a specification. It may be a bug.

Well, actually you can fix this problem.
Try the code below. You were using v2, right? If you are using v1 or older v2, convert `hasOwnProp` to `haskey`
```ahk
OnError("errorHandler")
TraySetIcon("AHK_Gold_16x16.ico")
return

errorHandler(exception, reason)
{
    message := Format("{}:{} ==> {}", exception.file, exception.line, exception.message)
    if (exception.hasOwnProp("extra")) {
        message .= "`n Specifically: ". exception.extra
    }
    message .= "`n"
    OutputDebug(message)

    ExitApp
}
```

**Comment by SAbboushi** [comment] 2020-06-16 16:58
> This is not a problem. It is a specification.
Oops! Ottotto!

Thanks for your explanations and the education.  It seems I can send output to DEBUG CONSOLE that becomes a hyperlink to a file or line within file.  I wonder what the requirement is?

- I tested and it works with full path to a valid file with any extension 
- If I also want hyperlink to line number, format required seems to be: "<full path to file>:<line number>" without any spaces

Is this correct?  Is this a feature of your extension and your specification?  Or part of DBGp protocol?


> For paths with spaces, I've checked with the Node Debugger, but those paths have broken links.
> This was also true for paths that contained symbols (except for some underscores and hyphens).
> This is probably by design and cannot be fixed.

1) Do you know if this is bug with AHK, DBGp or something to do with vscode?

> For paths with spaces, I've checked with the Node Debugger, but those paths have broken links.
2) I am ignorant in this area... does this mean your extension is written in node.js?

3) I am curious if you are a registered user of [AutoHotkey forums](https://www.autohotkey.com/boards/)? If yes, will you share your user name with me: I am interested to see your posts.

4) I wonder if you post on AHK forum to report bugs or to get answers; also, to announce your very very good extension?

**Comment by zero-plusplus** [comment] 2020-06-17 00:48
> * I tested and it works with full path to a valid file with any extension
> * If I also want hyperlink to line number, format required seems to be: ":" without any spaces

I think it's correct.

I write each answer.

1. The link feature of Debug Console is a standard feature of vscode.

2. The answer is yes, but a little different.
The reason I refer to the node debugger is because it's a standard extension.

3. I have created the account itself. The name is the same `zero-plusplus`. However, I still can't post because my account is still locked because I didn't receive the activation email.

4. I can't read the intention a little because the translation doesn't work. Are you asking me if I plan to post bug reports etc on the Forum?
I may post if my account is verified.

**Comment by SAbboushi** [comment] 2020-06-17 17:49
> > For paths with spaces, I've checked with the Node Debugger, but those paths have broken links.
> > This was also true for paths that contained symbols (except for some underscores and hyphens).
> > This is probably by design and cannot be fixed.
> 
> 1. Do you know if this is bug with AHK, DBGp or something to do with vscode?

Also, I have requested Autohotkey admin to try and enable your user account.

**Comment by zero-plusplus** [comment] 2020-06-18 00:03
This is a vscode spec, not a bug
Look [here](https://github.com/microsoft/vscode/issues/98498)

It seems difficult to fix this problem, but it seems that there is intention to consider it, so if you request symbols other than brackets, you may be able to fix it.

> Also, I have requested Autohotkey admin to try and enable your user account.

sorry. I confirmed that my account was already activated.

**Comment by SAbboushi** [comment] 2020-06-18 02:46
> This is a vscode spec, not a bug
> Look [here](https://github.com/microsoft/vscode/issues/98498)

Thanks - what about the spaces?

**Comment by zero-plusplus** [comment] 2020-06-18 09:30
look [here](https://github.com/microsoft/vscode/issues/97941)

This is also added to the fix plan.

**Closed** 2020-06-18 10:03 UTC

**Comment by SAbboushi** [comment] 2020-07-14 17:45
I have made [enhancement request](https://www.autohotkey.com/boards/viewtopic.php?f=13&t=78571) in AHK Forum

**Comment by zero-plusplus** [comment] 2020-07-15 06:11
Thanks for the report.

**Comment by SAbboushi** [comment] 2020-07-17 17:03
lexikos responded: [https://www.autohotkey.com/boards/viewtopic.php?f=13&t=78571&p=342418#p342272](https://www.autohotkey.com/boards/viewtopic.php?f=13&t=78571&p=342418#p342272)
