### ISSUE TITLE
[enhancement] A_DebuggerName := ""; not treated as Global variable inside function

### ISSUE THREAD

**Issue by SAbboushi** [zero-plusplus/vscode-autohotkey-debug#22] opened 2020-07-11 02:51 UTC
[AHK V2 will require variables to be initialized in future](https://lexikos.github.io/v2/docs/commands/_Warn.htm).

I like to use `A_DebuggerName` for when I am debugging, but it results in Warning when I am not debugging and running the script:
![image](https://user-images.githubusercontent.com/1964198/87214941-c5882a00-c2f6-11ea-8484-0d7dce167b2e.png)

Possible to make `A_DebuggerName` read-only so I can initialize it in script; then there should be no Warning when running the script:
```
A_DebuggerName := ""
if A_DebuggerName
    _var1 := "a`tb`nc"
else
    _var1 := 234
    msgbox _var1

```

**Comment by zero-plusplus** [comment] 2020-07-11 04:10
You can solve this problem by using an [IsSet](https://lexikos.github.io/v2/docs/commands/IsSet.htm).

```ahk
if IsSet(A_DebuggerName) && A_DebuggerName
    _var1 := "a`tb`nc"
else
    _var1 := 234
msgbox _var1
```

**Comment by SAbboushi** [comment] 2020-07-11 12:02
Thank you!  Good solution

**Comment by SAbboushi** [comment] 2020-12-04 14:45
It seems that even though `A_DebuggerName` is listed as a Global variable, it is not treated as a Global variable in function:
![image](https://user-images.githubusercontent.com/1964198/101176934-cf475c80-360c-11eb-9358-b42b2752c1fc.png)

```
if ( x1 := IsSet(A_DebuggerName) ) && ( x2 := ( A_DebuggerName = "Visual Studio Code" ))
    test1()

test1()
{
    if ( x1 := IsSet(A_DebuggerName) ) && ( x2 := ( A_DebuggerName = "Visual Studio Code" ))
        MsgBox( A_Args )
}
```

**Comment by zero-plusplus** [comment] 2020-12-05 04:21
Come to think of it, I forgot about that specification.
The problem is caused by the debugger's inability to define a [SuperGlobal](https://www.autohotkey.com/docs/Functions.htm#SuperGlobal) variable.

There are actually two types of global variables in AutoHotkey.

SuperGlobal variables, like many other languages, can be defined once and are available to all functions. For example, classes and built-in variables.
However, if you want to use a regular global variable that is not, you have to redeclare it in your function using the `global` keyword.

I forgot about this specification because I don't use regular global variables.
I'll add note that in the README.


This problem can be solved by adding the following code to the [auto-execute section](https://www.autohotkey.com/docs/Scripts.htm#auto)
```ahk
global A_DebuggerName := A_DebuggerName ; Elevated to SuperGlobal
```

**Comment by zero-plusplus** [comment] 2020-12-24 14:49
I checked the source code, and it still seems that there is no way to write variables in a super-global.

You can check below, but it seems that only local and global are supported.
* https://github.com/Lexikos/AutoHotkey_L/blob/master/source/Debugger.cpp#L1675
* https://github.com/Lexikos/AutoHotkey_L/blob/522e83eee0287cf02388aff179b3fcb6da33d268/source/Debugger.h#L180

Since there is nothing more I can do, I will close this issue.

**Closed by zero-plusplus** 2020-12-24 14:49 UTC

**Comment by SAbboushi** [comment] 2020-12-25 15:04
good research.  thanks for sharing
