### ISSUE TITLE
[Documentation, v1.6.8] links to document e.g. #breakpoint-directive not working

### ISSUE THREAD

**Issue by SAbboushi** [zero-plusplus/vscode-autohotkey-debug#94] opened 2021-03-13 15:44 UTC
![image](https://user-images.githubusercontent.com/1964198/111035373-e356e300-83df-11eb-8622-042a34f99fc3.png)

Does not work for me, nothing happens when I click links to sections within the document e.g. "Output Directive"

**Comment by zero-plusplus** [comment] 2021-03-14 01:12
All the links do not work for me.

This issue is fixed by downgrade the VSCode version (Confirmed in 1.45.0), so I think it may be a bug on the VSCode side.

In order to solve this issue with the latest version of VSCode, need to recreate `state.vscdb`.
However, it seems to be a recurring bug as I have done that and now have the same issue.

**Closed** 2021-03-19 10:49 UTC
