### ISSUE TITLE
Runtime not detected

### ISSUE THREAD

**Issue by anonymous1184** [zero-plusplus/vscode-autohotkey-debug#77] opened 2020-12-10 19:25 UTC
Unless I specify an executable on a folder other than %ProgramFiles%\AutoHotkey I keep getting this error:

```
runtime is not AutoHotkey runtime.
Specified: "C:\Program Files\AutoHotkey\AutoHotkey.exe"
```

https://i.imgur.com/QDrMOup.png

Win10 v20H2 | VSCode v1.51.1 | AHK v1.1.33.2

**Comment by zero-plusplus** [comment] 2020-12-11 02:44
I am using machine translation.

In my environment, there was no problem.
Please let me know what launch.json you are using.

Also, please make sure that AutoHotkey.exe is placed correctly.
You can check this by type `C:\Program Files\AutoHotkey\AutoHotkey.exe` in the path at the top of Windows File Explorer and enter.
If it is correctly placed, a document file (chm) will open.

**Comment by anonymous1184** [comment] 2020-12-12 01:36
File is there, normal AutoHotkey installation. This is the default:

```json
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "ahk",
            "request": "launch",
            "name": "AutoHotkey Debugger",
            "program": "${file}",
            "stopOnEntry": true
        }
    ]
}
```

And I've tried variations with the slash and the U32/U64 version:

```json
            "runtime": "C:/Program Files/Autohotkey/AutoHotkey.exe"
            "runtime": "C:\\Program Files\\Autohotkey\\AutoHotkey.exe"
            "runtime": "C:\\\\Program Files\\\\Autohotkey\\\\AutoHotkey.exe"
            "runtime": "C:/Program Files/Autohotkey/AutoHotkeyU64.exe"
            "runtime": "C:\\Program Files\\Autohotkey\\AutoHotkeyU64.exe"
            "runtime": "C:\\\\Program Files\\\\Autohotkey\\\\AutoHotkeyU64.exe"
```
Still, no luck (even when running VSCode elevated).

**Comment by zero-plusplus** [comment] 2020-12-12 01:48
I understood.
The sample you provided is probably the one used by [AutoHotkey Plus](https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-autohotkey-plus).

Please check if you can start it with the following settings:
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "autohotkey",
            "request": "launch",
            "name": "AutoHotkey Debugger",
            "program": "${file}",
            "stopOnEntry": true
        }
    ]
}
```

This problem is caused by conflicting debugging functions.
In other words, there are two default settings, one provided by my extension and one provided by AutoHotkey Plus.

**Comment by zero-plusplus** [comment] 2020-12-12 02:01
The above solution was off the mark. It probably will not solve the problem.
The only difference I know of between the environments is the Windows version, but I don't think that is the cause either.

I will try to find the cause.

**Comment by anonymous1184** [comment] 2020-12-12 04:39
Same thing, just downloaded a clean VSCode to reduce possible issues, Installed just `slevesqe-autohotkey` and `vscode-autohotkey-debug`

https://i.imgur.com/QW10Q4q.png
https://i.imgur.com/RYa2Sp9.png
https://i.imgur.com/9hbyOYb.png

**Comment by zero-plusplus** [comment] 2020-12-12 05:05
Thanks for the additional information.

AutoHotkey detection has been implemented in 1.6.2.
So please check if debugging works correctly with a lower version (e.g. 1.6.1).

On a different note, you can upload images directly to Github Issues without having to use imgur.

**Comment by anonymous1184** [comment] 2020-12-12 07:25
The ImgUr is just a hotkey convenience, if I snap something auto-uploads and I get the URL in clipboard, force of habit.

And finally cracked the issue:
https://github.com/zero-plusplus/vscode-autohotkey-debug/blob/a10446d0b2c7840b1e783e03016786434b4b34f3/src/util/getAhkVersion.ts#L35
Signed executables are not recognized. I use the signed versions as default because I need UI Access enabled so I sign AHK binaries and "compiled" scripts with my own cert. If the binaries are not signed there's no issue.

**Comment by zero-plusplus** [comment] 2020-12-12 07:51
Oh I see. I checked and it seems that there was an EACCES error.
I wish there was a workaround to allow debugging even with UIAccess enabled.

I'll add a note to the README about this issue.
Thank you for the report.

**Comment by anonymous1184** [comment] 2020-12-12 18:15
That's a bummer, basically I cannot debug if I don't have UI Access. Why other extensions are able to use the signed binaries? (i don;t have any expertise with this)

**Comment by zero-plusplus** [comment] 2020-12-13 02:28
It's probably a security limitation of NodeJS [spawn](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options).

So far, [this extension](https://marketplace.visualstudio.com/items?itemName=helsmy.autohotkey-debug) is the only one that can work around this issue.
The main part of it uses AutoHotkey, so it seems to be able to work around the above limitation.

This means that can work around this problem by replacing the script startup process with AutoHotkey instead of spawn.

However, the process of replacing TypeScript with AutoHotkey is a bit time-consuming because of the escape sequences and other processing required.
I don't have much time at the moment as I'm working on the early release of another extension that supports AutoHotkey.

I promise to fix this issue when it is settled. (That is if I can solve it using the above method...)

**Comment by zero-plusplus** [comment] 2020-12-13 02:40
I opened #78 which solves this problem. Therefore I will close this issue.

It will be at least next year before this issue is resolved. Until then, please use the stock AutoHotkey or use the extension above.

**Closed by zero-plusplus** 2020-12-13 02:40 UTC

**Comment by anonymous1184** [comment] 2020-12-17 00:51
Thanks a lot buddy.

**Comment by zero-plusplus** [comment] 2021-01-17 14:17
I tried to challenge this issue, but found it difficult to implement in its current state.
I am planning a large-scale refactoring in the future and will redesign the extension to make it easier to solve this problem at that time.

There is no set schedule for this refactoring.
This is because I have a lot of work to do on the other extension described above, and I don't have time to do it.

Even if this can be implemented, it is likely to be more restrictive than normal debugging, and since SciTE4AutoHotkey or another extension can solve this issue, I may abandon the implementation if it is too restrictive. Please understand this.

**Comment by zero-plusplus** [comment] 2021-09-23 08:45
There was a big delay in the planning, and this issue has been avoided in `1.8.0`, although it was delayed.

**Comment by anonymous1184** [comment] 2021-09-24 00:20
This is beyond amazing, I no longer have to do a few workarounds for this. Infinite thanks!

**Comment by zero-plusplus** [comment] 2021-09-24 02:31
I'm glad you found it useful.

Due to the [limitations](https://github.com/zero-plusplus/vscode-autohotkey-debug#about-uia-version-of-autohotkey) regarding standard output, if you want to output logs, please use [OutputDebug](https://www.autohotkey.com/docs/commands/OutputDebug.htm) or use the [debug directive](https://github.com/zero-plusplus/vscode-autohotkey-debug#debug-directive-optional).
