### ISSUE TITLE
[bug?] Intellisense Code Completion behaving oddly

### ISSUE THREAD

**Issue by SAbboushi** [zero-plusplus/vscode-autohotkey-debug#76] opened 2020-12-05 15:02 UTC
Intellisense doesn't display `A_Clipboard` until I type the "o"
![Intellisense Code Completion for A_Clipboard 2020-12-05_08-56-13](https://user-images.githubusercontent.com/1964198/101246366-88bf3400-36d8-11eb-91f9-3e3c55100357.gif)

**Comment by zero-plusplus** [comment] 2020-12-05 16:13
I am not involved in intellisense except when debugging. So it could be a VSCode-specific problem.

From the image, I'm guessing that a snippet is suggested first, and then a word (auto-generated by VSCode) that is present in the code when the o is entered.

When I checked, for some reason I only see the snippets and not the word suggestions in the code.

I checked with VSCode v1.45.0, which I had prepared to test this extension, and it did not have this problem.

Perhaps my extension is not involved.

**Comment by zero-plusplus** [comment] 2020-12-24 14:51
A new version of VSCode has been released but still the same problem still occurs?

Please check if it still occurs if I turn off my extensions.

**Comment by SAbboushi** [comment] 2020-12-25 14:56
Using vscode Version: 1.52.1:
dudelmoser.vscode-autohotkey2, Version: 0.2.0
Editing AHK v2 code:

> Please check if it still occurs if I turn off my extensions.

With your extension off, `A_Clipboard` appears after typing `a_`

When I turn off your extension:
![image](https://user-images.githubusercontent.com/1964198/103137304-6d1ecc00-468d-11eb-81c4-f143a85e2997.png)

When I turn on your extension:
![image](https://user-images.githubusercontent.com/1964198/103137326-9dff0100-468d-11eb-92df-616399debf75.png)

Also, I see additional information to the right of each entry when your extension is on which makes me wonder if the problem is dudelmoser language file?
![image](https://user-images.githubusercontent.com/1964198/103137464-e7038500-468e-11eb-97b0-ff39385fb3d9.png)

**Comment by zero-plusplus** [comment] 2020-12-25 15:11
Thanks for the report.

I prepared the same environment and confirmed that the same problem occurs.
It certainly looks like my extension is causing the problem.

I don't know why this problem occurs since I am only adding items to the autocomplete database and not manipulating other items.

I will do some research on autocomplete specification.

**Comment by zero-plusplus** [comment] 2020-12-25 15:29
Fixed the issue. it seems that the API was not being used properly.

It was a bug that I probably wouldn't have been able to find, so it was very helpful to have it reported.
Thank you very much!

I'll upload a new version soon.

**Comment by SAbboushi** [comment] 2020-12-25 15:50
Good work!

**Comment by zero-plusplus** [comment] 2020-12-25 15:55
I'm sorry. What was displayed was a snippet with the name A_Clipboard, which I had registered before for confirmation.

Apparently this problem has not been fixed yet. I will continue to investigate.

**Comment by zero-plusplus** [comment] 2020-12-25 16:18
The strange thing about this problem is that it happens even if turn off all the features of the extension.

**Comment by zero-plusplus** [comment] 2020-12-25 16:52
I think this problem also occurs when installing the following extensions, although they are for v1.
* [cweijan.vscode-autohotkey-plus](https://marketplace.visualstudio.com/items?itemName=cweijan.vscode-autohotkey-plus)
* [helsmy.ahk-simple-ls](https://marketplace.visualstudio.com/items?itemName=helsmy.ahk-simple-ls)

Both implement IntelliSense.
The same is true for JavaScript, but I am concerned that word suggestions are turned off when IntelliSense is implemented.

**Comment by SAbboushi** [comment] 2020-12-25 17:09
strange/odd

**Comment by zero-plusplus** [comment] 2020-12-25 17:25
After removing unnecessary properties in package.json and testing with autocomplete turned off, this problem was resolved.

However, when I turned autocomplete back on, the problem occurred. It seems that this problem occurs when the CompletionItemProvider class for defining autocomplete is registered to VSCode.

I have not yet determined whether this is a VSCode specification or not, but there is a possibility that it cannot be solved at present.
It seems to be a problem that will take some time to solve at least.

Hmmm...JavaScript doesn't suggest words, so maybe it's a spec?

**Comment by zero-plusplus** [comment] 2020-12-25 17:39
I can't say for sure because I don't understand English correctly, but it may have something to do with [this issue](https://github.com/microsoft/vscode/issues/21611) with VSCode.

**Comment by SAbboushi** [comment] 2020-12-26 10:30
I read through the thread but am not knowledgeable enough regarding autocomplete vs. intellisense vs. word completion and different types of providers...

This seems very complicated...

**Comment by zero-plusplus** [comment] 2020-12-26 13:50
Speaking of which, can you confirm this issue with VSCode 1.45?
The word suggestion feature seems to be working fine in my environment.

**Comment by SAbboushi** [comment] 2020-12-26 15:41
I only had copy of 1.45.1 (could not find where to download 1.45; I could only find source code on github)
Yes: works different in 1.45.1

1.45.1
![image](https://user-images.githubusercontent.com/1964198/103154555-a58ddb00-475d-11eb-8dc1-ad8087141be4.png)


1.52.1
![image](https://user-images.githubusercontent.com/1964198/103154530-7d05e100-475d-11eb-8968-74cb6fdad9be.png)

**Comment by zero-plusplus** [comment] 2020-12-27 06:55
Thanks for the confirmation.
I guess it's a bug or spec in VSCode current version.

I close this issue and set an unresolved label. This label which will be removed when VSCode resolves this issue.

**Closed by zero-plusplus** 2020-12-27 06:55 UTC
Labels: unresolved

**Comment by zero-plusplus** [comment] 2021-03-14 06:16
In vscode-autohotkey, which is currently under development, word-based suggestions have been completely eliminated regardless of the VSCode version.
Apparently, when a language feature provides suggestions, it overrides the word-based suggestions. So it seems that language functions need to provide word-based suggestions.

It is very strange that the language feature is responsible for this, even though there is a setting like `editor.wordBasedSuggestions` to show the word base or not.

I need to investigate this issue a bit more.

**Comment by SAbboushi** [comment] 2021-03-14 10:30
OK
