### ISSUE TITLE
Settings ignored when script is selected in editor.

### ISSUE THREAD

**Issue by RaptorX** [zero-plusplus/vscode-autohotkey-debug#242] opened 2022-08-01 04:39 UTC
Issue Type: <b>Bug</b>

# Steps
* Create a launch.json script
* Create an ahk script
* Add conditional break (= 500)
* Press F5 to debug

<details>
<summary>Settings configuration</summary>

```
{
        // Use IntelliSense to learn about possible attributes.
        // Hover to view descriptions of existing attributes.
        // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
        "version": "0.2.0",
        "configurations": [
                {
                        "name": "AutoHotkey Debug (Advanced Configuration)",
                        "type": "autohotkey",
                        "request": "launch",
                        "program": "${workspaceFolder}\\src\\script.ahk",
                        "args": [],
                        "port": "9002-9010",
                        "variableCategories": "recommend",
                        "useDebugDirective": true,
                        "useAutoJumpToError": true,
                        "runtime_v1": "AutoHotkey.exe",
                        "runtime_v2": "v2/AutoHotkey.exe",
                        "useAnnounce": "error",
                        "useOutputDebug": {
                                "useTrailingLinebreak": true
                        }
                }
        ]
}
```

</details>

# Expected
Only output debug messages

# Result

![image](https://user-images.githubusercontent.com/328761/182073570-bbf71e4b-a941-4b20-9c7c-edd29617d094.png)

---

![image](https://user-images.githubusercontent.com/328761/182073590-44e9daea-3f1a-4abb-8ab8-31c6fe82a768.png)

# Notes
When pressing `F5` while a different file is selected the expected result happens every time.

---

Extension version: 1.11.0
VS Code version: Code 1.69.2 (3b889b090b5ad5793f524b5d1d39fda662b96a2a, 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz (4 x 3198)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (21.38GB free)|
|Process Argv|D:\\Cloud\\RaptorX\\Dropbox\\Guests\\the-Automator\\Client Work\\EveryDayCPA\\WokeInfo --crash-reporter-id bdc99747-9c48-41d5-87e2-d320011e638b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30438360
pythonvs932:30410667
wslgetstarted:30449410
vscscmwlcmt:30465135
cppdebug:30492333
pylanb8912:30529769
vsclangdc:30486549
c4g48928:30535728

```

</details>

**Comment by zero-plusplus** [comment] 2022-08-01 06:47
> * Add conditional break (= 500)

Does this mean [Hit conditional breakpoint](https://github.com/zero-plusplus/vscode-autohotkey-debug/wiki/Hit-conditional-breakpoint)?

**Comment by zero-plusplus** [comment] 2022-08-03 04:31
I could not confirm the issue in my environment.

Please make sure your debug configuration is set up correctly. (In this example `AutoHotkey Debug (Advanced Configuration)`)

**Comment by RaptorX** [comment] 2022-08-04 17:39
> Does this mean [Hit conditional breakpoint](https://github.com/zero-plusplus/vscode-autohotkey-debug/wiki/Hit-conditional-breakpoint)?

correct

> I could not confirm the issue in my environment.
> 
> Please make sure your debug configuration is set up correctly. (In this example `AutoHotkey Debug (Advanced Configuration)`)

I sent my current configuration in the first post (folded in spoiler tags named Settings configuration). I think it is correct.

**Comment by zero-plusplus** [comment] 2022-08-05 20:25
In my environment, `useAnnounce` is applied without any problem.

Can you provide a minimal example folder containing launch.json etc that can reproduce this issue?

Example folder should be zipped and uploaded directly to this Issues.
Uploading can be done by drag-and-drop.

**Comment by tomkahn** [comment] 2022-09-25 20:55
Maybe I can help as I have a similar issue: The following setting is ignored whenever I currently view a different .ahk file in VS Code:
`"program": "${workspaceFolder}\\main_script.ahk"`

For example when I'm currently viewing "library.ahk" and hit F5, that file is run. What I want is that no matter what file I'm currently viewing the main_script.ahk is run.

It's not an issue when I currently view launch.json and hit F5. Then the main_script.ahk is run.

The selected debugging profile is correct:
![image](https://user-images.githubusercontent.com/38276038/192165091-f15128ea-f109-4b0f-8d69-b3b10aeadeba.png)

Here is a folder to reproduce the issue:
[debugging_settings_ignored.zip](https://github.com/zero-plusplus/vscode-autohotkey-debug/files/9641734/debugging_settings_ignored.zip)

**Comment by zero-plusplus** [comment] 2022-09-26 06:09
Thanks for the information.

As a result, I did not see the problem in my environment and the `main_script.ahk` was always executed.

Do you have other extensions installed that provide debugging?

**Comment by tomkahn** [comment] 2022-09-26 09:53
You're welcome. These are my activated plugins:

![image](https://user-images.githubusercontent.com/38276038/192246626-f48eac38-8278-4edc-89df-758977ef4e80.png)
![image](https://user-images.githubusercontent.com/38276038/192246689-faa650c4-1175-4140-a487-ddc13dc4903e.png)

I had another AHK debug plugin installed before (I think it was AutoHotKey Debug) but it wasn't activated and I uninstalled it now. The issue remains the same.

**Comment by zero-plusplus** [comment] 2022-09-26 11:09
Please disable all AutoHotkey extensions except vscode-autohotkey-debug and then install the following extensions (For some reason it is marked as deprecated on vscode and cannot be installed)

* https://marketplace.visualstudio.com/items?itemName=slevesque.vscode-autohotkey

The extensions in the above links are simple extensions consisting only of syntax highlighting, so there will be no conflicts between extensions.

Please check if the same problem occurs in that situation.

**Comment by tomkahn** [comment] 2022-09-27 07:34
Ok, the reason was that [AutoHotkey v2 Language Support](https://marketplace.visualstudio.com/items?itemName=thqby.vscode-autohotkey2-lsp&ssr=false#overview) also adds a keyboard shortcut for F5 and that this one was taking priority over your extension. If you resolve this conflict and make sure that your extension is actually run, everything works as intended. ✔️

Sorry for taking up your time and thank you for the support! 😌

**Comment by zero-plusplus** [comment] 2022-09-27 11:23
Thank you for your confirmation work!
I am closing this issue as it is not an issue with this extension.

Please report back to us if you have any further problems. 👍

**Closed** 2022-09-27 11:23 UTC
